### PR TITLE
Firewizard updates rogy

### PR DESCRIPTION
**Pull request by rogy**
firewizards PR with edits too:

* re-adding magento version under feature flag
* sku_code required, keeping product ID the same as firewizards recommendation (sku code can end up as a duplicate of ID, this is fine)
* updated some old branding (QuBit is now Qubit)

### CODE REVIEW

**Comment by rogy** [comment]
@firewizard made a few edits that I have to stick too my side, look ok?

**Comment by rogy** [comment]
Also, I had started implementing the 'configurable product' switch on the product pages (but on the old style implementation before your updates)

If you see: https://github.com/QubitProducts/UniversalVariable-Magento-Extension/blob/updates-rogan-2/app/design/frontend/base/default/template/qubit/uv_configurable.phtml

You can see the way I was going for, do you think this is a smart way to go forward?

**Comment by firewizard** [comment]
@rogy, here's my feedback:
* you forgot a `print($data);` in `app/code/community/QuBit/UniversalVariable/Model/Uv.php` on line 61
* not sure if you needed to move the `getSku` line outside the if. if I understood the specs correctly, sku and stock info should be displayed together: http://docs.qubitproducts.com/uv/specification/#additionalpropertiesforproductsrequiringstockkeeping - there's not _required_ to any of these
* voucher field is a string, not an array: http://docs.qubitproducts.com/uv/specification/#additionalpropertiesforproductswithpromotions
* the `show_magento_version` label and comment are missing from the csv
* i see you changed all texts to Qubit, shouldn't the namespace change as well? that's a camel-case too
* why did you remove the modman file?

**Comment by firewizard** [comment]
regarding configurable products, i can't really say for sure as I don't know what `getCustomOptions` is supposed to do. The approach might work, but then again, i'm not sure if it has to be done this way. i'll think about it over the next days. Personally, I'd merge everything without the configurable part and work on that with the new coding style.

**Comment by rogy** [comment]
Hi @firewizard 

- good spot, thank you
- Yes, understood, just the way we do it just now requires to always have access to the SKU, so we don't want to have a situation where they use the product ID and not stock, so we cannot access SKU
- See http://docs.qubitproducts.com/uv/specification/#basket and transaction pages, vouchers should be an array of strings, i know in the Magento case by default it only allows one, but just to keep it standard doing this works (this was requested by a colleague to change this to an array like the spec)
- thank you 
- namespace isn't too important as it won't be seen by anyone but developers really, easier than updating the whole fire structure
- accidental - I'd never actually used modman and now I can't stop!

regarding the configurable, absolutely will put that in another PR.

**Comment by firewizard** [comment]
sorry, my bad, i was looking at the product specs, where `voucher` is not an array, but a string.

**Pull request merged**
