### PR TITLE
refactored plugin for a more Magento-style coding approach

### PR DESCRIPTION
**Pull request by firewizard**
* added new admin options for hiding stock info, product id, user id
* simplified template code
* removed magento version from UV object for security reasons
* removed observer, no need for it
* added Uv model for generating the UV object
* added translation file

### CODE REVIEW

**Comment by rogy** [comment]
Many thanks for this!

I will go through it and hopefully merge it over the next few days, few questions before I deep dive.

- Any chances of reduced compatibility with older Magento versions?
- I'd be interested in know what your security reasons for removing the Version are!
- Did you mean to include that modman file?

Again many thanks for taking the time to contribute

**Comment by firewizard** [comment]
* Ideally, this should have unit tests and use travis. that way it's easy to spot incompatibilities. unfortunately tests take a while to write so they'll probably have to wait. 

	from the top of my head, i'm 99% sure it works on any CE version greater than 1.5 (including). It should work just fine on CE 1.4 and EE, as it uses basic code.

	if there are bugs, those would be visible on any magento ce 1.5+

	there are also a lot of things to add and a few others to refactor even more

* having the version number is not a security issue per se, but removing it helps tightening things up a little bit. Here's the reason behind it: http://en.wikipedia.org/wiki/Security_through_obscurity

	additionally, the magento version of a store is not really dynamic. it only changes on upgrades, so i don't really see a use case for it.

* yes, the modman file has  a few updates to reflect the changes (module filename change, translation file).

There are few things to be added, and hopefully nothing major to fix - after all I'm using this version on a live website. I'd like to add some events for allowing users to extend the functionality easier, but I haven't yet analyzed that part. There are a few missing tags from the `listing ` implementation, and they would be useful, but implementing them is rather quirky. Unit testing and CI are some other good additions, too. When time allows it, I'll work on these and push the changes.

**Comment by rogy** [comment]
I will collaborate with my peers to try and get to the reasoning behind the inclusion of the version number in the first place and review this one.

There are a fair few changes I had written but as of yet unreleased but I will try re-writing them into this new structure, things like dynamically updating the stock and price in the UV for products with configurable options. And adding products currently on page to the listing object (this is under an option flag as I think it probably has the worst hit on performance)

I'm not massively up to date with Magento module practices, but I would be interested to know if you had any thoughts around speeding the module up? This is one of my main focuses at the moment for the future of the module.

Again, many thanks.

**Comment by firewizard** [comment]
Adding those missing vars for listings shouldn't have any kind of impact regarding speed. everything is already loaded, so that's what it should be used. however, there are few problems with the layer singleton and the toolbar block which might raise some difficulties, but hopefully someone will figure it out.

And you're right, configurable products and custom options are not yet implemented and those will definitely take a while to add and test (there are countless scenarios there)

Regarding the speed of the plugin, I didn't notice anything major. The only bottlenecks I see are with the 'product' object which loads two categories. Nothing fancy, but for large collections and large databases it might slow things down a bit. I wouldn't worry about it at the moment though.

**Pull request merged**
